### ISSUE TITLE
Empty web part zones module

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#1]

**Comment by petrsvihlik** [comment]
Do you suggest parsing zone IDs from `PageTemplateLayout` and then matching them with XML in the `PageTemplateWebParts` column of `CMS_PageTemplate`?

**Comment by ondrejsevcik** [comment]
Yes, that's the only approach I know that should work.

**Comment by ChristopherJennings** [comment]
This is now handled in the Page Template Overview module
