### ISSUE TITLE
Create export functionality

### ISSUE THREAD

**Issue by JosefDvorak** [Kentico/KInspector#104]
I would like to create export functionality that would allow me to generate an editable report with data of selected modules.

This report should support exchangeable templates and should be further modifiable so that the results can be further modified.

The suggested output format is .docx (`application/vnd.openxmlformats-officedocument.wordprocessingml.document`), as it can be both modified and later converted to pdf.

The main goal is to create a human readable report.

**Comment by petrsvihlik** [comment]
We have to look for a OS-friendly rendering library (license-wise).
In case we decide to go with PDFs, a friend of mine recommended using https://github.com/tuespetre/TuesPechkin. It uses chromium for rendering and handles CSS well.

**Comment by petrsvihlik** [comment]
Fixed in https://github.com/Kentico/KInspector/pull/115
