### ISSUE TITLE
API for getting values from web.config

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#11]

**Comment by petrsvihlik** [comment]
In different modules, we are retrieving various parts of the web.config. I don't think there is enough space for generalization and we should just use `ConfigurationManager`. https://msdn.microsoft.com/en-us/library/system.configuration.configurationmanager(v=vs.110).aspx
If you agree, please close the issue.

**Comment by ondrejsevcik** [comment]
yes I agree. Let's stick with simplicity.
