### ISSUE TITLE
Keep history of instances

### ISSUE THREAD

**Issue by JosefDvorak** [Kentico/KInspector#118]
### Motivation

The connection form caches the last instance you connected to, but you need to manually change instance information in the connection form if you want to connect to a different one. This means that if you switch between multiple instances, you need to keep updating the connection dialogue.

### Proposed solution

It would be nice to be able to save instance history for later re-connection with a simple "save for later" checkbox before connecting.

The target config is currently stored in the browsers local storage. Adding the checkbox could add the current settings to an array of configurations in local storage. which would be displayed in the connection dialog.

**Comment by ChristopherJennings** [comment]
Will be included in #180
