### ISSUE TITLE
Creating new KInspector module - Need Kentico file access

### ISSUE THREAD

**Issue by WakeflyCBass** [Kentico/KInspector#119]
I’m trying to build a KInspector module to scan Media Library items, and identify any database records that exist for Media Library files that are missing from the filesystem (for example, if the media library folder has changed) – without such a module, those files just disappear from the Media Library interface so it’s hard to know if you found all of your files. (https://docs.kentico.com/display/K9/Settings+-+Media)  

I’ve already written code to go to the database and check the Media settings (to figure out the base folder for the media library) – but since KInspector doesn’t run within the context of the Kentico site, I can’t just run ‘File.Exists’ or ‘VirtualPathProvider.FileExists’ . Does anything exist within KInspector that could help with getting file access, or even getting the Kentico server's context so that I can check the virtual paths? 

I've created the new module in this fork:
https://github.com/WakeflyCBass/KInspector/tree/Media-File-Consistency-Module.

**Comment by ChristopherJennings** [comment]
Hi @WakeflyCBass,

Thanks for the contribution. The first thing I want to mention is that the base folder for the instance is available in the `instanceInfo` object passed to the `GetResults` method. From there you can use the `Directory` object's `FullName` property to get the base directory and use `File.Exists()` like normal. 

The second thing you'll want to consider is whether the media library items are stored there at all. For example, they might be moved outside the instances base folder (e.g. in a UNC path, separate drive, or blob storage). These scenarios may be outside the scope of what you were thinking, but the module should at least gracefully handle those situations by indicating that the system cannot verify those. A simple warning might be sufficient, but I'd prefer that the tool identify that and not perform the tests if it detects those configurations (unless you add support for them).

**Comment by WakeflyCBass** [comment]
My intent is to handle all three cases - for a server path, or absolute filepath, I don't need to know the Kentico folder - it's only needed for the relative-path case (~/). I believe (hope?) that in the other two cases File.Exists() will return properly without further tweaking.

I didn't think to look in instanceInfo before - is there documentation on what that object holds?

I will have a warning in the comment that if this app doesn't have permissions to see the files, that it will misreport - but I imagine in the majority if not all of cases, if an end user has permission to see the files, that KInspector should, too.
