### ISSUE TITLE
Enable compatible modules for Kentico 10

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KInspector#123]
- test modules against K10
- enable those that work
- adjust those that don't (or create new issues if fixes require more effort)

pseudo code of what needs to be done:

```
clone the repository
for each (module in https://github.com/Kentico/KInspector/tree/master/KInspector.Modules)
{
  add new Version("10.0") to SupportedVersions array
  if(module returns correct data)
  {
    leave the supported version in
  }
  else
  {
    try
    {
      fix the module while not breaking it for older versions
    }
    catch
    {
       remove "10" from the supported versions array
       create new issues in this repository if the fix requires more effort
    }
  }
}
commit the changes

```

**Comment by ileshmistry** [comment]
Hello 

I was just wondering when we might expect this to be V10 compatible? I am trying to look at a few new K10 sites to make them KInspector-fied, but noticed we couldn't use it fully. 

Thanks
Ilesh

**Comment by petrsvihlik** [comment]
Hi @ileshmistry ,
as soon as someone picks up the issue. 
@ChristopherJennings any plans on assigning it to someone internal?
@ileshmistry you or someone from MMT can pick it up if you want. I can explain what needs to be done. Actually, I'll update the description of this issue right away.

**Comment by ileshmistry** [comment]
Thanks @petrsvihlik if you can let us know what might need doing, we can go from there :)

**Comment by ChristopherJennings** [comment]
@petrsvihlik & @ileshmistry,
Unfortunately, there isn't really any bandwidth right now for someone internal to take this on unless they do it on their own time. @petrsvihlik has updated the description with a good summary of what needs doing. @ileshmistry, Please leave a comment here if you or someone on your team plans to tackle this so we don't accidentally end up with duplicated effort.

**Comment by ileshmistry** [comment]
@petrsvihlik @ChristopherJennings giving this a go and will tackle each module at a time

**Comment by petrsvihlik** [comment]
@ileshmistry highly appreciated!
