### ISSUE TITLE
[Consistency issues] Database consistency check gives error

### ISSUE THREAD

**Issue by ileshmistry** [Kentico/KInspector#128]
We get the following error when 'Error in "Database consistency check" module. Error message: Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.' when running this task. 

Our database size is 47.73GB, we have had this in the past on other projects too. 

Thanks
Ilesh

**Comment by ChristopherJennings** [comment]
This module doesn't do anything complex. It just  runs `DBCC CHECKDB WITH NO_INFOMSGS, EXTENDED_LOGICAL_CHECKS, TABLERESULTS` and returns the results. This will perform a deadlock on tables, so be sure that nothing else is using the database. 

Given that, there's not really anything we can do within KInspector to address this. Do you have any suggestions on how we might better handle the failure? Perhaps updating the error message to indicate that you might need to run the command manually?

**Comment by ileshmistry** [comment]
I think updating the error message to run it manually would be good. But then it would need to make sure it is clear warning that the user would need to resolve. And providing hints or the code to run this manually will help.

**Comment by ChristopherJennings** [comment]
That's an excellent set of ideas. I've created separate issues for more detailed errors and the error message for this specifically (see above references).

**Comment by ileshmistry** [comment]
@ChristopherJennings thanks, this sounds good :)
