### ISSUE TITLE
"Important scheduled tasks" does not check correct keys for Kentico 9.0

### ISSUE THREAD

**Issue by rshackleton** [Kentico/KInspector#140]
The "Delete inactive contacts" SQL query checks for these keys:

- CMSEnableOnlineMarketing
- CMSDeleteInactiveContacts

However, Kentico 9 uses these keys for inactive contacts:

- CMSDeleteInactiveContactsLastXDays
- CMSDeleteInactiveContactsMethod

The SQL query needs to be updated to check for these keys to prevent returning an incorrect warning.

Tested with Kentico 9.0.35.

**Comment by ChristopherJennings** [comment]
@rshackleton, thanks for reporting this. I have confirmed the issue. Unfortunately, the way this module is currently written makes it hard to resolve without duplicating the large SQL file or deprecating the module for older versions of Kentico. 

I think the best way to resolve this would be to dramatically update the way this particular module checks and reports on the scheduled tasks. Do you have any thoughts or suggestions on how we might approach this? Are you willing to take ownership of this issue? I'm happy to brainstorm ideas to rebuild this module in a way that is more flexible. I'm currently thinking separate, parameterized SQL statements for each task that we need to check, but I'm open to other ideas.

**Comment by amarquez914** [comment]
Sounds like a good first issue for my foray into open source contribution. I guess we should brainstorm something @ChristopherJennings

**Comment by kentico-ericd** [comment]
As we are now mainly supporting K13, this is not applicable
