### ISSUE TITLE
Add more detail to "Disabled web parts and web part zones" module

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#147]
### Motivation

More details about the disabled web parts will help in determining which action to take to resolve the warning.

### Proposed solution

The module should identify the codename/title of web parts and web part zones that met the visibility false condition. This can be accomplished by:

1. Add the `PageTemplateWebParts` column to the SQL query so we can do further processing in code.
2. Parse the contents of the column to an XML document
3. Select all the property elements that match our condition (`<visibility>False</visibility>`)
4. Determine is the parent node is a web part or a web part zone. 
5. Track the results of found web parts and web part zones separately
6. Change the returned results to be two tables. One for web parts and one for web part zones. Both should include the page template display and code name as well as the web part or web part zone display and code name.

**Comment by kentico-ericd** [comment]
As we are now mainly supporting K13, this is not applicable
