### ISSUE TITLE
Replace console with GUI

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#150]
The primary purpose of this is to enable more advanced configuration of the self-contained web server and provide a way to show more advanced status messaging. 

Instead of running the site in a console window, KInspector will launch in a GUI window (Xamarin App). It will expose options for changing the server port, launching the browser, and a log window for messages that were previously sent to the console. 

This will enable us to add enhancements to the server portion of KInspector down the road.

**Comment by petrsvihlik** [comment]
Will there be any downsides of this transition? 
For instance, I won't be able to analyze a web project through my cell phone...but does it really matter?
Shouldn't the app be rather a Xamarin app (supporting also UWP)?

**Comment by ChristopherJennings** [comment]
I don't see any downsides to moving away from a console hosted application. 

As for UWP, while we could probably make the switch, the main point of this is configuration for the KInspector server instance. This is currently only desktop-type environments. 

However, once we complete #151 it would make more sense to make this a Xamarin app, as we could add remote server connections to allow users to configure remote KI instances.

**Comment by ChristopherJennings** [comment]
(I've updated the original comment to indicate Xamarin APP instead)

**Comment by petrsvihlik** [comment]
Exactly my thoughts!

**Comment by ChristopherJennings** [comment]
Rolled into #180
