### ISSUE TITLE
Enable KInspector.Web project to run in IIS 

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#151]
The KInspector.Web project is a self-hosted .NET Core application, but is not currently compatible with IIS. By enabling this to run in IIS without the accompanying console window will enable easier use in remote scenarios and on developer machines.

**Comment by petrsvihlik** [comment]
It's not a .NET Core app, afaik. (Or at least wasn't when I last checked.)

It's an OWIN self-hosted app.

Shouldn't we first attempt a transition to .NET Core + .NET Standard?

**Comment by ChristopherJennings** [comment]
Correct. It is not a .NET core app; it is an OWIN self-hosted application. 

For this project I don't see any benefit in transitioning to .NET Core at this stage. Kentico EMS is not able to run in .NET Core, so the environment will always be Windows/IIS at this stage. 

There has been some community interest in being able to run this on a dev integration server in IIS to audit sites without having to run the app/connect remotely.

**Comment by petrsvihlik** [comment]
sounds reasonable

**Comment by ChristopherJennings** [comment]
Will be covered in #180
