### ISSUE TITLE
Gather anonymous usage telemetry?

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#152]
In order to better understand how KInspector is being used, we should consider collecting *anonymous*, *opt-in* telemetry about what modules are run, what errors are encountered, and what versions of Kentico are being analyzed. 

We welcome the communities thoughts on this idea.

**Comment by petrsvihlik** [comment]
I'd start with a blogpost on devnet to collect the basic data (used versions, etc.)
It's been quite some time since the last post about kinspector, so we could share some news (what's been implemented, what's the future plan)...

**Comment by ChristopherJennings** [comment]
Agreed. This would be a great first step. 

I still think there's value in telemetry as this would further clarify which reports people are using. Maybe adding a "was this helpful" survey at the end of each report would help gather info in the moment.
