### ISSUE TITLE
Issue with Kentico v10.0.13 and WorkflowConsistencyModule.cs

### ISSUE THREAD

**Issue by dominikpinter** [Kentico/KInspector#160]
Hey, I believe I found an issue with WorkflowConsistencyModule.cs. On the line 226 there is a XPath Expression which looks like this:

XmlNodeList fields = xml.SelectNodes("/NewDataSet/Table1/*");

However, with K10.0.13 my structure of the document xml is the following:

<NewDataSet>
  <XYZ_ABC>
   </XYZ_ABC>
</NewDataSet>

where XYZ_ABC is the name of my page type. I guess that older versions of Kentico had there just "Table1" and that's why xpath expression worked but now I get workflow inconsistency errors even though document looks fine (fields are there). After updating locally to more general XPath:

XmlNodeList fields = xml.SelectNodes("/NewDataSet/*/*");

The code started to work as I expected (fields in the xml were found) and my workflow consistency issues were gone.

**Comment by ChristopherJennings** [comment]
Looks like your XML got dropped from the comment. Regardless, it sounds like you've got a fix. Would you mind creating a pull request so we can review and pull it in? If you need assistance with that I'm happy to help.
