### ISSUE TITLE
Kentico 7 sites report missing tables and classes

### ISSUE THREAD

**Issue by ChristopherBass** [Kentico/KInspector#163]
### Brief bug description

When running the "Class table validation" module on a Kentico 7 instance, the tool reports several tables without Kentico classes and a couple of classes without tables. It appears that these are "ghosts" of development that were never cleaned up.

### Repo steps

1. Connect to a Kentico 7 instance
2. Run the "Class table validation" module
3. Observe that the following Kentico-created tables are shown as missing a Kentico class definition:
    - Analytics_ExitPages
    - Analytics_Index
    - CMS_Session
    - CMS_WebFarmServerTask
    - OM_ScoreContactRule
4. Observe that the following Kentico classes are shown as missing database tables:
    - Ecommerce - SKU option
    - Ecommerce - Variant option

### Expected behavior
The above classes/tables are added by Kentico in a clean installation and shouldn't be reported as problematic.

### Screenshots
http://prntscr.com/i7vu3q

### Resolution steps
Update the logic in `ClassTableValidation.cs` as follows:
1. Update `GetTableWhitelist` method to return the five tables that are missing when the Kentico version is 7
2. Add new `GetClassWhitelist` method to whitelist the v7 classes conditionally and update the `GetResults` method appropriately.

**Comment by ChristopherJennings** [comment]
This warrants further investigation. Thanks for bringing this up!

**Comment by ChristopherJennings** [comment]
I finally got around to confirming this. I think it's safe to say these are "ghosts" of features that were added/removed in that version and never cleaned up. I'm going to update the issue description to indicate that we should whitelist/blacklist these in v7.

**Comment by ChristopherJennings** [comment]
This was resolved, but the PR got closed by someone else before it was merged after a long hiatus. With V4 being the focus and only planning to support 10+, I'm going to close this. If you'd like to patch the current V3 module, feel free to request that #182 be re-opened.
