### ISSUE TITLE
Ensure compatibility with Kentico 11

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KInspector#164]
Similarly to #123 

Perhaps @ileshmistry might be interested to help out again? :)

**Comment by ileshmistry** [comment]
@petrsvihlik Sure I can help out on this one

**Comment by sultanwork77** [comment]
Is this up for Kentico-11 now?

**Comment by petrsvihlik** [comment]
@sultanwork77 this item hasn't been implemented yet. would you be interested in helping out?

**Comment by sultanwork77** [comment]
@petrsvihlik 
I have done changes internally by cloning master and creating an internal branch. I have added support for version 11 where ever the support for 10 was present and ignored where there was not. Now problem is that am unable to push that branch. am getting errors as 
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.

**Comment by petrsvihlik** [comment]
@sultanwork77 you need to fork KInspector under your account, clone it locally, make changes, push the changes to a branch in your fork and then submit a pull request. 
see the video here: https://www.youtube.com/watch?v=ixGakcfITe8

**Comment by sultanwork77** [comment]
@petrsvihlik 

Done as suggested by you and raised a pull request
Committing support version for Kentico-11 #165

**Comment by Enngage** [comment]
I think we should make this a higher priority because its only a matter of time when we will really need this for K11. Actually, I'm writing here because I already do:)

**Comment by ChristopherJennings** [comment]
Forgot to update this issue. This was addressed in PR #165, which has been merged into master. There is one outstanding issue #167, that should be addressed, but the main functionality is there. Closing this issue.
