### ISSUE TITLE
Check for password policy/encrtyption

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#17]
This is a simple task that is meant to be picked up by newcomers. Check out http://www.firsttimersonly.com/.

Steps to be taken:
- [fork the repository](https://help.github.com/articles/fork-a-repo/)
- clone it to your local machine, you can use [Visual Studio](http://www.malgreve.net/2014/06/17/cloning-getting-code-from-git-repository-to-visual-studio/), [GitHub desktop](https://help.github.com/desktop/guides/contributing/cloning-a-repository-from-github-desktop/) or [command line](https://help.github.com/articles/cloning-a-repository/)
  - we recommend using [GitHub extension for Visual Studio](https://visualstudio.github.com/)
- open your local clone with Visual Studio
- [create a new module](https://github.com/Kentico/KInspector/wiki/Writing-a-custom-module)
- implement the **logic** which consists of 2 checks:
  - check whether the `CMSUsePasswordPolicy` keys in the `CMS_SettingsKey` table are set to `true`. if not, return `ModuleResults` with status Warning (see [documentation](https://docs.kentico.com/display/K82/Password+strength+policy+and+its+enforcement))
  - check whether the `CMSPasswordFormat` key in the `CMS_SettingsKey` table is set to `SHA2SALT`. if not, return `ModuleResults` with status Error (see [documentation](https://docs.kentico.com/display/K82/Password+encryption+in+database))
- check whether your code complies with our [contribution guidelines](https://github.com/Kentico/Home/blob/master/CONTRIBUTING.md)
- push your changes to your fork (VS->Team Explorer->Changes->Commit&Sync)
- create a PR and include Fixes #17 in the message

We'll review the change and either merge right away it or suggest potential changes.
If you have any questions feel free to ask in the repository chat [![Join the chat at https://gitter.im/Kentico/KInspector](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Kentico/KInspector?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by petrsvihlik** [comment]
`CMSUsePasswordPolicy` setting is site specific

https://i.imgur.com/XxAwi31.png.

We don't count with it in a code. We need to

Check for every CMSUsePasswordPolicy value
Maybe it would be good to display also SiteName along with KeyName and KeyValue

**Comment by anibalvelarde** [comment]
I'm not familiar with KI's data structures yet, so please excuse the question if it is too trivial. 

In your opinion, what would be the best source for _SiteName_?  I was wondering if said value, _SiteName_, could be obtained from the `CMS_SettingsKey` table or the `InstanceInfo` parameter coming into the `PasswordPolicyModule.GetResults(InstanceInfo)` method. 

Knowing this piece of info can help me contribute to fixing this bug quicker than if I have to investigate for myself.

**Comment by martbrow** [comment]
I believe you'd need to check in the CMS_Site table for the name, SiteDisplayName looks more useful than SiteName to identify the site.

I believe the following would get the information needed.

SELECT ISNULL(CMS_Site.SiteDisplayName,'N/A') as SiteDisplayName, CMS_SettingsKey.KeyName, CMS_SettingsKey.KeyValue
FROM  CMS_SettingsKey LEFT OUTER JOIN
         CMS_Site ON CMS_SettingsKey.SiteID = CMS_Site.SiteID
WHERE (CMS_SettingsKey.KeyName IN ('CMSUsePasswordPolicy', 'CMSPasswordFormat'))

It'd be easy then to loop through the DataRow[] passwordPolicyRow (variable should now I guess be pluralised) to see if any of the values are not True.

**Comment by petrsvihlik** [comment]
@anibalvelarde: @martbrow is correct.

**Comment by petrsvihlik** [comment]
When fixing this, please take into account the following comment: https://github.com/Kentico/KInspector/pull/66#issuecomment-172516990
