### ISSUE TITLE
Password policy settings incorrect recommendation

### ISSUE THREAD

**Issue by kentico-ericd** [Kentico/KInspector#171]
The Password policy settings module will flag CMSPasswordFormat when set to PBKDF2. It claims _"The CMSPasswordFormat should be set to 'SHA2SALT'"_ but our documentation states that PBKDF2 is the most secure option: https://docs.kentico.com/k10/securing-websites/designing-secure-websites/securing-user-accounts-and-passwords/setting-the-user-password-format

**Comment by ChristopherJennings** [comment]
Duplicate of #161, whic hwas fixed in PR #168, and released in version 3.8
