### ISSUE TITLE
Add a check for CMSEnableCsrfProtection into SecurityAppSettingsModule.cs

### ISSUE THREAD

**Issue by bayotop** [Kentico/KInspector#172]
### Motivation 

CSRF Protection should not be disabled. 

### Proposed solution

Add a check to `SecurityAppSettingsModule.cs` to check that `CMSEnableCsrfProtection` App Settings Key is `true`. This can be done the same way the check for `CMSRenewSessionAuthChange` is done.

**Comment by amoraitis** [comment]
Working on it

**Comment by petrsvihlik** [comment]
Hi @amoraitis , I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.
