### ISSUE TITLE
Returns an empty string and causes next line to fail

### ISSUE THREAD

**Issue by bkehren** [Kentico/KInspector#174]
https://github.com/Kentico/KInspector/blob/5b0b952aeb59601d2feb69399f58125289e2e432/KInspector.Modules/Modules/General/ClassTableValidation.cs#L40

On line 40 of ClassTableValidation.cs, when running the "[Database] Class table validation" module against a version 9.x install, the GetTableWhitelist() method returns an empty string and causes line 41 to fail with the following error:

"Error in "Class table validation" module. Error message: Syntax error: The IN keyword must be followed by a non-empty list of expressions separated by commas, and also must be enclosed in parentheses."

**Comment by ChristopherJennings** [comment]
Doh. Looks like we should put some conditional logic on https://github.com/Kentico/KInspector/blob/5b0b952aeb59601d2feb69399f58125289e2e432/KInspector.Modules/Modules/General/ClassTableValidation.cs#L41
to only do the select if `formattedWhitelist` has a value.

@bkehren, are you interested in taking a stab at this or should we mark this as up for grabs?

**Comment by bkehren** [comment]
I can handle the fix @ChristopherJennings.  Check the Kentico Community Slack channel when you get a chance.

**Comment by ChristopherJennings** [comment]
Merged into master. Will be included in next release. Thanks! See any other issues that catch your fancy?
