### ISSUE TITLE
Ensure compatibility with Kentico 12 MVC

### ISSUE THREAD

**Issue by ileshmistry** [Kentico/KInspector#195]
It would be good to get this working for Kentico 12 MVC sites

**Comment by ChristopherJennings** [comment]
Any MVC-specific reports you would expect? 

We are currently working on a major rewrite for V4. The initial release of that will likely only be to support most existing modules, add K12 support for all relevant modules, and add a few new features. New reports (such as those focused on MVC) would come after the initial release.

**Comment by ileshmistry** [comment]
I think initially for it to work with K12 would be good for us to get an initial start to use it. 

Happy to wait until after the first release

**Comment by ChristopherJennings** [comment]
Just for further context, the new version will actually allow you to run reports on any version unless they are explicitly known to be incompatible. This should help with forward compatibility in the future. 

I'm going to go ahead and close this as it will be addressed as part of the rebuild.
