### ISSUE TITLE
 REST - authentication mode and SSL

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#21]
https://docs.kentico.com/display/K82/Authenticating+REST+requests
https://docs.kentico.com/display/K82/Configuring+SSL
https://docs.kentico.com/display/K82/Securing+the+Staging+and+REST+web+services

**Comment by ChristopherJennings** [comment]
This is not clear on what the expected module would look like. Please feel free to re-submit with more details on the expected benefits/outcomes.
