### ISSUE TITLE
Add warnings to page template summary report

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#228]
### Motivation

Help developers identify common issues that crop up in page templates. 

### Proposed solution

- Implement errors/warnings for the following identifiable common issues:
  - [ ] No caching/partial caching on data source and repeater web parts
  - [ ] No columns on generic data source and repeater web parts (unless using a custom query or data source)

### Additional context
- More research needed to identify specific error/warning conditions
Add any other context, screenshots, or reference links about the feature request here.
- Blocked by #227

**Comment by kentico-ericd** [comment]
As we are now mainly supporting K13, this is not applicable
