### ISSUE TITLE
Enable toggling of Admin SSL

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#237]
### Motivation

Make it easy to reconfigure backups that are configured for SSL when you don't have SSL in the current environment.

### Proposed solution

Enable easy toggling of SSL in admin via the "Security Settings Analysis" via a button.

### Additional context

Blocked by #204 & #210

**Comment by kentico-ericd** [comment]
As we are now mainly supporting K13, this is not applicable
