### ISSUE TITLE
Automatic detection of the Azure (Database, Blob storage)

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#26]
Modules meant for running in Azure environment should not be loaded if the analyzed instance isn't running in Azure. Currently [MediaLibraryAzureLimitModule.cs](https://github.com/Kentico/KInspector/blob/master/KInspector.Modules/Modules/General/MediaLibraryAzureLimitModule.cs) and [BigTablesAzureModule.cs](https://github.com/Kentico/KInspector/blob/master/KInspector.Modules/Modules/General/BigTablesAzureModule.cs). 

We should be able to recognize Azure environment by looking into the web.config.

**Comment by petrsvihlik** [comment]
I suggest implementing some kind of "capabilities" feature based on which some modules wouldn't get loaded. E.g. modules requiring Azure, modules dependent on InstanceInfo.Directory or InstanceInfo.Uri.

**Comment by ChristopherJennings** [comment]
Created a spike for this in #179
