### ISSUE TITLE
Check for broken links in pages

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#3]

**Comment by petrsvihlik** [comment]
Out of the scope of this project imho. And there already is a linkchecker in kentico (Validate tab). I vote for closing this.

**Comment by ondrejsevcik** [comment]
The Validate tab checks for dead links just on a current page. If your web has a more than 10000 pages, you don't want to do it for every page.

But I agree. We shouldn't spend time on something that already exists. 
- http://www.brokenlinkcheck.com
- http://www.deadlinkchecker.com
- http://www.drlinkcheck.com

I'm just thinking whether we should mention those sites somewhere in the KInspector or not.

**Comment by petrsvihlik** [comment]
I think this is a general website development topic rather than something kentico-related. We could write a blogpost about it though...

**Comment by ondrejsevcik** [comment]
Maybe we can mention those websites in a description of "Not found errors (404)" module. What do you think?

**Comment by petrsvihlik** [comment]
Good idea!

**Comment by ondrejsevcik** [comment]
Resolved in #53. Closing this issue.
