### ISSUE TITLE
Content tree consistency analysis report fails when there are pages using a folder page type

### ISSUE THREAD

**Issue by yuriys-kentico** [Kentico/KInspector#324]
### Brief bug description

Content tree consistency analysis report fails when there are pages using a folder page type, which has no table.

### Repro steps

1. Use an instance with pages using a page type that is a folder
2. Run the report

### Expected behavior

Report produces a result

**Comment by kentico-ericd** [comment]
Closing- can't reproduce on Dancing Goat sample site
