### ISSUE TITLE
Split "Analysis" category to at least 2 new categories

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KInspector#41]
It's too busy on the Analysis page. I suggest splitting it to:
**Analysis - Health**
- stuff like "Application restarts", "Event log errors"

**Analysis - Performance**
- stuff like "Attachments by size", "Maximum 100 files per folder in Azure Blob storage"
  Analysis - whatever's needed

It should also be easier to distinguish between modules that are meant to give you just overview (like e.g. "[General] Top 25 tables by size") and ones that actually inspect certain aspects of Kentico and make recommendation based on the results (like "[Content] Duplicate Page Aliases").

**Comment by ChristopherJennings** [comment]
Included in new spike to rebuild the UI (#180)
