### ISSUE TITLE
Add validations to the setup screen

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KInspector#49]
E.g. URL is not validated and can later result in an exception...
So URL, filesystem path and database should all be validated...

**Comment by Charlotteis** [comment]
Hi @petrsvihlik, organise of @yourfirstpr here. Would you be able to provide some explanation of what you are looking for? As it stands, I'm not confident someone seeing this Issue for the first time would know what to do.

Have a great day!

**Comment by petrsvihlik** [comment]
Thanks @Charlotteis , you have a good point. I've adjusted all our first-timers-only and up-for-grabs issues (https://github.com/Kentico/KInspector/labels/first-timers-only) and closing this one because it's not really relevant.

**Comment by Charlotteis** [comment]
Thank you so  much, this is brilliant! :)
