### ISSUE TITLE
Add Gitter 'open chat' button into the main application

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#55]
Gitter supports embedding chat window into the page with a little JavaScript snippet. I tried it and it looks good. Maybe we can collect some feedback through this channel.

@petrsvihlik What do you think?

![2015-11-10 20_55_37-kinspector](https://cloud.githubusercontent.com/assets/4136929/11074026/b7ca9838-87ed-11e5-8383-5d24399e9761.png)
![2015-11-10 20_55_14-kinspector](https://cloud.githubusercontent.com/assets/4136929/11074025/b7c35802-87ed-11e5-8fcd-23efaa8b108e.png)

**Comment by petrsvihlik** [comment]
:+1: looks perfect

**Comment by petrsvihlik** [comment]
@ondrejsevcik did you close it intentionally?

**Comment by ondrejsevcik** [comment]
Yes, I was thinking about this and it's not the best way to collect feedback because a lot of KInspector users simply doesn't have GitHub account. 

Maybe we can setup simple email alias or mailing list.
