### ISSUE TITLE
Use of CurrentDocument vs CurrentPageInfo Module

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#6]
CurrentPageInfo has a better performance.

Locations to check
- macros (of any kind)
- web part property, 
- transformation
- layout (page template, web part)
- HEAD section of master template 
- ...

**Comment by jokob** [comment]
I don't think you'd have to narrow it down that much... a simple list where the CurrentDocument (.NodeAliasPath, .DocuemntID etc.) object is used should be enough... for that a simple search thru all files and all DB tables and columns would be sufficient... It would take a bit longer, depending on the available data, but it would be a good start (can be sped up by excluding certain tables/fields)...later the module can  be improved further

**Comment by ondrejsevcik** [comment]
Yes, as a first version it could be enough, but we can also brainstorm some common locations where it can occur and make this issue ready for the first timmers.

**Comment by ChristopherJennings** [comment]
Tracking in #178
