### ISSUE TITLE
Check for disabled web parts

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#7]
This is a simple task that is meant to be picked up by newcomers. Check out http://www.firsttimersonly.com/.

Steps to be taken:
- [fork the repository](https://help.github.com/articles/fork-a-repo/)
- clone it to your local machine, you can use [Visual Studio](http://www.malgreve.net/2014/06/17/cloning-getting-code-from-git-repository-to-visual-studio/), [GitHub desktop](https://help.github.com/desktop/guides/contributing/cloning-a-repository-from-github-desktop/) or [command line](https://help.github.com/articles/cloning-a-repository/)
  - we recommend using [GitHub extension for Visual Studio](https://visualstudio.github.com/)
- open your local clone with Visual Studio
- [create a new module](https://github.com/Kentico/KInspector/wiki/Writing-a-custom-module)
- implement the **logic**:
  - search the `PageTemplateWebParts` column in the `CMS_PageTemplate` table for `<property name="visible">False</property>`
  - if you find any records inform the user by returning `ModuleResults` with status Warning and a table with results
- check whether your code complies with our [contribution guidelines](https://github.com/Kentico/Home/blob/master/CONTRIBUTING.md)
- push your changes to your fork (VS->Team Explorer->Changes->Commit&Sync)
- create a PR and include Fixes #7 in the message

We'll review the change and either merge right away it or suggest potential changes.
If you have any questions feel free to ask in the repository chat [![Join the chat at https://gitter.im/Kentico/KInspector](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Kentico/KInspector?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
### Watch how to contribute to KInspector on YouTube

[![Check out KInspector on YouTube!](http://img.youtube.com/vi/ixGakcfITe8/0.jpg)](http://www.youtube.com/watch?v=ixGakcfITe8)

**Comment by nileshleve** [comment]
I would like to claim this issue!!

**Comment by ChristopherJennings** [comment]
Go for it. I'm looking forward to your pull request!

**Comment by CasperRademaker** [comment]
Dear @ondrejsevcik and @ChristopherJennings,

Thank you for giving newcomers a chance to learn. I took the liberty of working on this issue and I believe my code is almost done. 

I'm just not sure how to run proper tests. The current tests seem to test the class "PasswordPolicyModule" specifically. Are we supposed to write our own tests, are can we use any functionality that is already provided?
I also see a test class named "InstanceInfoTests" but I am not sure how to test based on that class.

Help on this is kindly appreciated,

Casper

**Comment by ChristopherJennings** [comment]
Hi @CasperRademaker,

Given that the other contributed never moved forward with this, it's absolutely fine for you to grab this. 

As for testing, we've been really lax on that. Feel free to re-use stuff that's there or wrote something of your own. 

Almost no modules actually have tests, and we need to get a better strategy in place for that, but right now there's no strict requirement to have tests. If a pull request has them, awesome, but we're not going to reject a working module that doesn't have tests at this point. 

Thanks for your efforts. Im looking forward to your pull request!
