### ISSUE TITLE
Screenshotter doesn't work with FF43

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KInspector#72]
* doesn't work with FF43 (at least on my machine) and throws an exception :white_check_mark: Fixed in https://github.com/Kentico/KInspector/pull/75
* should check whether FF is installed (or perhaps try to use different drivers)
* should not throw exceptions if FF fails to start -> it should rather log/print an error
* should save the screenshots to a subfolder and not to desktop directly :question: needs to be investigated

**Comment by ondrejsevcik** [comment]
By default, it saves screenshots into the subfolders named by url.
e.g.: `c:\users\ondrej\desktop\http_localhost_kentico9\http_localhost_kentico9\_getdoc_5f78f8d2-87f8-4649-8aff-ca5d84d7fa54.jpg`

**Comment by petrsvihlik** [comment]
Yeah, I see the code now. However, it happened once to me that the application started creating screenshots all over my desktop. Maybe it occurs when `InstanceInfo.Uri` is empty or something like that. Needs further investigation....

**Comment by ondrejsevcik** [comment]
Closing this issue. All the problems are mentioned in #76.
