### ISSUE TITLE
Review and update module names and descriptions

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KInspector#73]
Sometimes it's difficult to say what the module does and what does its output mean. They deserve better descriptions and recommendations.

Examples:
[Security] Vulnerability analyzer - it doesn't mention it checks for sql injections, XSSs, etc..
[Security] WebPart analyzer - again - what vulnerabilities it checks for? what does the output mean? can we make it a little bit more readable?
[General] CMSFile usage check - "Checks whethere there are unneccessary CMSFiles in the content tree" - what unnecessary means? (+the typos)
[General] Screenshotter - what is its purpose? + https://github.com/Kentico/KInspector/issues/72

[General] Important scheduled tasks - what is "important" and improve recommendations
[Social marketing] Expired tokens - what is the module about? what kind of tokens are we talking about?
[General] Site map - what is the purpose of this module?
[General] Unspecified 'columns' setting in web parts - what exactly are "ID"s in the output? specify - PageTemplateID...

**Comment by WakeflyCBass** [comment]
Now that you can view the comments on a module before actually running the module, is this issue solved by adding any extra information, within the comment?

**Comment by petrsvihlik** [comment]
@WakeflyCBass yeah, this is just about adjusting/improving the descriptions to be more informative.

regarding the hyperlinks, don't hesitate to create a new issue. we can discuss the details there :)

**Comment by ChristopherJennings** [comment]
This issue is currently too broad. We will be revisiting names, descriptions, etc. as part of the V4 rebuild. Closing for now. If specific issues arise after V4 launch, we can address them then.
