### ISSUE TITLE
Consolidate *password* modules

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KInspector#74]
There are currently four modules that are related to passwords in some way.
- [Security] Password policy settings
- [Security] Security settings
- [Security] Users with empty passwords
- [Security] Users with plaintext passwords

We should consolidate those to a single "Password" report. (The Security settings module will remain as it contains also other stuff.)

**Comment by ondrejsevcik** [comment]
Agree! It will be much clearer for users.

**Comment by ChristopherJennings** [comment]
New issues created as part of the V4 migration.
