### ISSUE TITLE
Remove UIElementsDiff module

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#77]
The UIElementsDiff module is kind of prototype (not working as expected and needs a lot of improvements). The question is whether somebody makes use of this module. 

@ChristopherJennings how about you and your team?

**Comment by ChristopherJennings** [comment]
We've used it, but I didn't find it particularly helpful. Probably due to the fact that it is a prototype...

**Comment by ondrejsevcik** [comment]
This module is searching for differences in UIElements between default installation and customer instance. The problem is that to do the comparison, it needs a database snapshot of every released version (including hotfix). Right now, the snapshots are saved as XML files in https://github.com/Kentico/KInspector/tree/master/KInspector.Modules/Data/DefaultUIElements folder. But we don't have enough time/resources to prepare database snapshot for every released version and hotfix and I believe you guys don't have too. 
There might be also another issue displaying diff properly for upgraded instances. 

Because of this, I don't see much value in this module and I would rather remove it. If someone want's to implement it properly, he can start from the scratch. 

What do you say @petrsvihlik, @ChristopherJennings?

**Comment by petrsvihlik** [comment]
@ondrejsevcik what you say makes sense to me. however, i don't have strong opinion on removing it. it depends on how much is the module used. if users don't find it useful at all i'd be for removing it. otherwise we could keep it and perhaps provide a how-to on preparing the comparison xml files.

**Comment by ondrejsevcik** [comment]
We don't know how much is this module used, because we don't have any tracking mechanism, but I believe it's not used at all as it doesn't have very good description and results.

**Comment by petrsvihlik** [comment]
go ahead then... :)

**Comment by ondrejsevcik** [comment]
I talked with Miro and he also confirmed that this module is not used anymore. I will remove it.
