### ISSUE TITLE
Improve page analysis

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#8]
Measure for each page
- number of SQL queries called
- number of scripts/links/images in the page
- first request response time vs. second (caching)

**Comment by petrsvihlik** [comment]
How do you suggest the implementation should look like? Some kind of crawler that would go through all pages and drill the data from...from? :) This could be quite lengthy operation...
Don't we have enough information in Kentico->Debug application?

**Comment by ondrejsevcik** [comment]
We already have a crawler that hits every page in Kentico (page analysis module). It's a lengthy operation, but it could be handy to have a first vs. second response time for each page. This way you can see if the website uses cache or not.

Also for the scripts/links/images all you have to do is a parse HTML output and search for the ```<script>``` ```<img>``` and ```<style>``` tags. It will not be a 100% as some pages can load scripts/images/styles via JavaScript but I believe that in most cases it will be good enough. 

For the SQL queries, I don't have an idea how to implement it.
