### ISSUE TITLE
Missing script for Workflow consistency

### ISSUE THREAD

**Issue by jamesbloor** [Kentico/KInspector#86]
Downloading latest release 3.0.0, installing, and running the 'Workflow consistency' module gives the following error:

Error in "Workflow consistency" module. Error message: Could not find file 'C:\Temp\KInspector\Bin\Scripts\WorkflowConsistencyGetDocuments.sql'.

With C:\Temp\KInspector being the root directory of my install.

**Comment by ondrejsevcik** [comment]
Hi, I tried this as well with the same result as in #87.

**Comment by jamesbloor** [comment]
Hi @ondrejsevcik - I now get the same result as #87.

Very weird. Will close this down.

**Comment by ondrejsevcik** [comment]
I'm glad that we figured it out :+1:
