### ISSUE TITLE
Missing script for Number of document aliases module

### ISSUE THREAD

**Issue by jamesbloor** [Kentico/KInspector#87]
Downloading latest release 3.0.0, installing, and running the 'Workflow consistency' module gives the following error:

Error in "Number of document aliases" module. Error message: Could not find file 'C:\Temp\KInspector\Bin\Scripts\NumberOfAliasesModule.sql'.

With C:\Temp\KInspector being the root directory of my install.

**Comment by ondrejsevcik** [comment]
Hi @jamesbloor, 

I tried it and it's working on my machine. Are you sure that you have sufficient permissions to read from `C:\Temp\` folder? Can you try your desktop folder?

**Comment by jamesbloor** [comment]
Hi @ondrejsevcik - I've downloaded and extracted the zip again and it's working fine.

Must have been an error my end. Thanks.
