### ISSUE TITLE
Problem detecting site while comparing URLs in 'Detailed analysis of all rendered pages' module

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#89]
The **Detailed analysis of all rendered pages** module is liable to error while querying the database. It's because of the SQL query ([link to file](https://github.com/Kentico/KInspector/blob/master/KInspector.Modules/Modules/General/PagesAnalyzerModule.cs#L70))

``` SQL
SELECT s.SiteID 
FROM CMS_Site AS s 
LEFT JOIN CMS_SiteDomainAlias AS sa 
ON s.SiteID = sa.SiteID 
WHERE ('{0}' LIKE '%' + s.SiteDomainName + '%'
OR '{0}' LIKE '%' + sa.SiteDomainAliasName + '%') 
AND s.SiteStatus = N'RUNNING'
```

where the `{0}` part is replaced with values entered by user into the **Target setup** form. If the entered URL differs just in one character (e.g.: `http://domain.com/` vs. `http://domain.com`) this module throws an error: 

`Error in "Detailed analysis of all rendered pages (takes a while)" module. Error message: Null object cannot be converted to a value type.`

There should be some smarter logic to recognize the analyzed website.

**Comment by ChristopherJennings** [comment]
This was re-reported in #131 and fixed in #136
