### ISSUE TITLE
Check for enabled debug

### ISSUE THREAD

**Issue by ondrejsevcik** [Kentico/KInspector#9]
This is a simple task that is meant to be picked up by newcomers. Check out http://www.firsttimersonly.com/.

Steps to be taken:
- [fork the repository](https://help.github.com/articles/fork-a-repo/)
- clone it to your local machine, you can use [Visual Studio](http://www.malgreve.net/2014/06/17/cloning-getting-code-from-git-repository-to-visual-studio/), [GitHub desktop](https://help.github.com/desktop/guides/contributing/cloning-a-repository-from-github-desktop/) or [command line](https://help.github.com/articles/cloning-a-repository/)
  - we recommend using [GitHub extension for Visual Studio](https://visualstudio.github.com/)
- open your local clone with Visual Studio
- [create a new module](https://github.com/Kentico/KInspector/wiki/Writing-a-custom-module)
- implement the **logic** which consists of 2 checks:
  - check whether the web.config doesn't contain `debug="true"` in the [compilation element](https://msdn.microsoft.com/en-us/library/e8z01xdh.aspx?f=255&MSPPError=-2147217396) (we suggest using `ConfigurationManager` to do that)
  - check whether all boolean records in `CMS_SettingsKey` whose `KeyName` starts with CMSDebug are disabled (their `KeyValue` is false)
  - if any check fails inform the user by returning `ModuleResults` with status Error (debug should be disabled on production instances)
- check whether your code complies with our [contribution guidelines](https://github.com/Kentico/Home/blob/master/CONTRIBUTING.md)
- push your changes to your fork (VS->Team Explorer->Changes->Commit&Sync)
- create a PR and include Fixes #9 in the message

We'll review the change and either merge right away it or suggest potential changes.
If you have any questions feel free to ask in the repository chat [![Join the chat at https://gitter.im/Kentico/KInspector](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Kentico/KInspector?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
### Watch how to contribute to KInspector on YouTube

[![Check out KInspector on YouTube!](http://img.youtube.com/vi/ixGakcfITe8/0.jpg)](http://www.youtube.com/watch?v=ixGakcfITe8)

**Comment by ivydigitalstorm** [comment]
hi @ondrejsevcik i'm interested in working on this

**Comment by ondrejsevcik** [comment]
Hi @ivydigitalstorm, I'm glad to hear that. It's all yours 👍 

cc: @ChristopherJennings

**Comment by ChristopherJennings** [comment]
Hi @ivydigitalstorm,

Please refer to the previous pull request (#125). There were a few minor issues that prevented it from being accepted and it appears that the original PR has been abandoned. Please leave a comment on the pull request to see if they mind you taking this over. 

Thanks!
