### ISSUE TITLE
Custom macros analyser/reporter?

### ISSUE THREAD

**Issue by pnmcosta** [Kentico/KInspector#94]
Hi All,

Long time (>2 years) Kentico dev here, first time having a look at this project - I only wish I had found it earlier! Thank you support for the tip, and all contributors to it. :D

From what I've been reading so far, I think my problem could be solved either by an existing module (I haven't explored much but don't think there's any) or by creating and/or contributing with one.

So here's the issue I have, I've inherited a site in 5.5 that we've just finished converting to v8 (thank you support for your help with that as well) successfully, but the project makes heavy use of the old Custom macro expressions (see [# - Custom macro](https://devnet.kentico.com/docs/6_0/devguide/types_of_macros.htm#custom) in k6 docs).

We've converted the old code to a new macro namespace with fields for the old expressions, but now am wondering whether there is an easy way to dig the DB for any references to those old custom macros expressions?

Ideally it would also convert them to the new macro fields in the namespace we define, e.g. {#Expression#} to {%Namespace.FieldName%} but I'd be happy if the module could just report the web parts, templates and/or any other object that uses the old custom macro so we can manually go and change it.

Do you think this issue can be covered by module on Kinspector? Or is there one already? I'd be happy to contribute or start a new one if necessary, but would appreciate any kind of guidance.

Thanks,
P.

**Comment by pnmcosta** [comment]
edited because I realized I had used new macro fields instead of methods.

**Comment by pnmcosta** [comment]
ah! I've just realized that the upgrade has wrapped all the custom macros with ProcessCustomMacro

I was not aware of this when I started the upgrade, and incorrectly converted the code to a new macros namespace, instead of doing what in the comment from Kentico_RichardS here:
https://devnet.kentico.com/forums/f68/fp6/t41415/custom-macro-won-t-register


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CMS.SettingsProvider;
using CMS.GlobalHelper;
using CMS.CMSHelper;

```
/// <summary>
/// Summary description for CustomMacroLoader
/// </summary>
[CustomMacroLoader]
public partial class CMSModuleLoader
{
    /// <summary>
    /// Attribute class ensuring the registration of macro handlers.
    /// </summary>
    private class CustomMacroLoader : CMSLoaderAttribute
    {
        public override void Init()
        {
            // Assigns a custom macro resolving handler.
            MacroResolver.OnResolveCustomMacro += MacroResolver_OnResolveCustomMacro;
        }


        /// <summary>
        /// Resolves custom macros.
        /// </summary>
        /// <param name="sender">Sender</param>
        /// <param name="e">Event arguments representing the resolved macro</param>
        private void MacroResolver_OnResolveCustomMacro(object sender, MacroEventArgs e)
        {
            // Checks that the macro is not resolved yet.
            if (!e.Match)
            {
                // Defines the return values of specific custom macro expressions.
                switch (e.Expression.ToLower())
                {
                    // Handles the {% ProcessCustomMacro("CustomExpression", "") %} macro.
                    case "customexpression":
                        e.Match = true;
                        e.Result = "Resolved expression";
                        break;

                    // url 
                    case "myurl":
                        e.Match = true;
                        string url = HttpContext.Current.Request.QueryString["UserName"];
                        // get url
                        url = "Special user " + url;
                        e.Result = url;
                        break;  
                }
            }
        }
```

So I don't think it's an actual issue, at least not for me any more, but what do you think of a module that would still check for old macro references, do you see a case where that would be needed at all? I'd still be willing to contribute anyway.

**Comment by petrsvihlik** [comment]
Hi @pnmcosta, first of all, thanks for the positive feedback on KInspector. The utility is very much about best practices (or pointing out bad practices :)) so it makes sense to me to have a module that would detect old fashioned macros and reported them as warnings. The question is how to look them up. If I'm not mistaken we'd have to search literally all text fields in the DB because they can be (almost) everywhere. What are your thoughts?

**Comment by pnmcosta** [comment]
Hi @petrsvihlik, "we'd have to search literally all text fields" I would assume so, I'd also assume that the  System app on Kentico (where you resign macros) would have most of the logic for this. But KInspector (I'll be honest, forked it but not looked at the code yet ;) doesn't seem to use the same API as in Kentico - is that correct?

Is there any other module already that does something remotely similar to this? I'd probably also need the regex that was used on the older versions to resign these # - custom macros.

**Comment by petrsvihlik** [comment]
You are right, KInspector doesn't use the Kentico API at all...It's an SQL-based tool.
There is one module which searches for macros - `WebPartAnalyzerModule`. Have a look at it. It basically looks up brackets.
Regarding the regex, I couldn't find the original one but I think something like this `{#(.[^#}])*#}` would suffice...

**Comment by pnmcosta** [comment]
Ah great, will have a look, count me in :+1:

**Comment by pnmcosta** [comment]
Umm, if WebPartAnalyzerModule already does parts of this, I'm starting to thing this shouldn't be a module in itselft, but something that is applied in existing or new modules that analyse issues with a context where macros could be used.

For example the TransformationAnalyzerModule, already exists, we should append to it the ability to check if html/text macros don't have the custom macro.

And create a new EmailTemplatesAnalyzerModule that checks for common issues with email templates, as well as the custom macros.

I think this makes more sense than writing a grand module that checks everything, do you agree?

**Comment by petrsvihlik** [comment]
In general, I agree. Just a few remarks: 
- I'd vote for reusing as much "macro" logic across those modules as possible.
- Do you see any other important places we should check apart from webparts, transformations and email templates?

**Comment by pnmcosta** [comment]
Nice,

- Agreed, where would you like me to start? Modifying the WebPartAnalyzerModule, TransformationAnalyzerModule or create the suggested EmailTemplatesAnalyzerModule? And how do you propose we share these functionality? Simple static MacroValidationHelper, or do you have something else in mind?
- Will do as I find them ;) Anyone else care to share a few ideas where you'd like to have macro usage validated across versions?

**Comment by petrsvihlik** [comment]
I think abstracting the logic from `WebPartAnalyzerModule`, adjusting it to our needs and then using it in the `TransformationAnalyzerModule` would be a good approach as it would prove the point about re-usability. Then we can follow up with the `EmailTemplatesAnalyzerModule` in a next pull request.
Regarding the shared logic, I'd go with a singleton (e.g. `MacroValidator`) similar to `ProjectCodeFilesHelper` until we have implemented some kind of DI.

**Comment by pnmcosta** [comment]
Ok, great, I'll be working on this out-of-hours, but I estimate I should have something for you to review by the end of next week.

**Comment by petrsvihlik** [comment]
:+1: looking forward to it

**Comment by pnmcosta** [comment]
Ah, may have overestimated this :)

It's not tested yet, need to run it agains a v8.0+ with a deprecated custom macro, but I think the bulk of the abstraction of the logic to the macrovalidator can be found in this commit: https://github.com/pnmcosta/KInspector/commit/7803d94e3b51f0bbcac7e4fb0f14ebe4db84a56f

It's only on my dev branch still, but once it's properly test I'll merge it to master and create a pull request.

Have a great weekend.

**Comment by pnmcosta** [comment]
Tested successfully with a database that was just upgraded to v8, but not had it's first load after the upgrade:

![conditions-deprecated-macros](https://cloud.githubusercontent.com/assets/550684/15448979/ba6e680e-1f68-11e6-9802-8f69d8b4b610.JPG)

![content-deprecated-macros](https://cloud.githubusercontent.com/assets/550684/15448980/be539d36-1f68-11e6-87aa-8a31a2104afb.JPG)

**Comment by petrsvihlik** [comment]
Comments in the PR https://github.com/Kentico/KInspector/pull/95

**Comment by petrsvihlik** [comment]
I think you could proceed with the `EmailTemplatesAnalyzerModule` if you're willing to :)

**Comment by pnmcosta** [comment]
If it's ok with you, I'd rather close this one for now, and raise a new issue for the EmailTemplatesAnalyzerModule

That way if someone else would like to pick it up I wouldn't be holding anyone back.

Cheers,
P.
