### ISSUE TITLE
Workflow consistency module issue?

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KInspector#96]
I opened pull request #93, but closed it as it was not a complete solution. It appears that this was noted in the 3.2 release notes as included, but it is not actually included as the pull request was never merged with master. 

The core issue is that the SQL script for retrieving documents from the version history table assumes that all pages in the version history table have foreign keys, but certain page types (e.g. folder) do not. I added a simple null check to the SQL, but realized that it was not a complete solution, as those pages would just not get checked at all. 

I'll take another look at this in the future when I have more time, but if someone else wants to grab it in the meantime, that's find by me.

**Comment by ondrejsevcik** [comment]
Thanks for letting me know. I've removed it from 3.2 release and also from release notes.

**Comment by ChristopherJennings** [comment]
I started to look into this and found that it had been fixed in 6ba4854
